### ISSUE TITLE
Ganti tulisan di bagian CRF

### ISSUE THREAD

**Issue by dhana-exe** [danipragustia/MKVRipa#10]
di bagian CRF di sebelah kiri better quality
di sebelah kanan Better size... saya rasa lebih pas tulisannya Lower size deh pak...
entah kenapa agak janggal aja bacanya better size :3

**Comment by danipragustia** [comment]
Terima kasih atas sarannya.

https://github.com/danipragustia/MKVRipa/commit/80b00c939c4371dbabc2bccfdd502e63b2908dd8 update: WIP Watermark and some changes 

Saya akan tutup issue, untuk release akan sembari dengan fitur watermark.
