### ISSUE TITLE
Butuh update (ERROR)

### ISSUE THREAD

**Issue by dhana-exe** [danipragustia/MKVRipa#12]
Entah kenapa yang versi terbaru dipakek di laptop ku habis install ulang gak bisa sama sekali
Coba batch untuk 4 file MKV dari OBS auto close cmd nya....

**Comment by danipragustia** [comment]
Coba jalan file ``batch.bat`` (dalam folder MKVRipa) di cmd, trus kirim screenshot dsni.

**Comment by dhana-exe** [comment]
eh sudah fix
entah tadi aku uninstall apa sekarang udah bisa
