### ISSUE TITLE
[Ask][Bug][Maybe Request] Non-Subtitle or 2nd subtitle

### ISSUE THREAD

**Issue by dhana-exe** [danipragustia/MKVRipa#13]
Permisi pak
Barusan ntah kenapa dicoba untuk encode video biasa menjadi H265 tanpa subs dia gak mau yak? atau akunya yang error
kalau bisa kasih support juga/setting buat non-subtitle biar bisa di proses kan lumayan encodenya enak pakek ini daripada handbreak

selanjutnya untuk 2nd subtitle, untuk ini sub yang di hardsub in itu subtitle track pertama atau default indonesia dan kalau gak ada tag indo dia ke track 1?

yang mana mode nge-hardsub nya?
kalau otomatis search indo... berarti gak ada masalah
tapi kalau otomatis ke track pertama subs nya... soalnya temen ada yang mau nebeng hardsub in sesuatu ntar di masa depan
nah dia sub indonya yang mau di proses... sedangkan di mkv nya ada 3 subtitle nah itu gimana pak....

ntar klo yang kedua gak bisa... aku pakek cara delete aja sub nya baru ku proses gitu... siapa tau sama programnya bisa dipermudah daripada manual hehehe

**Comment by danipragustia** [comment]
- Bisa, saya akan buat checkbox untuk non-subtitle untuk versi selanjutnya.
- Default track pertama, sayang-nya tidak bisa (lebih tepat saya kurang tahu) gimana cara deteksi subtitle indo lewat ``FFMPEG`` CLI. (https://ffmpeg.org/ffmpeg-filters.html#subtitles).

Untuk point 2 jika agan temukan cara lewat FFMPEG bisa saya masukkan ke program.

**Comment by dhana-exe** [comment]
Untuk kedua coba ini pak
https://stackoverflow.com/questions/48159388/show-subtitles-list-get-id-and-name-of-each-subtitles-track
https://superuser.com/questions/700082/is-there-an-option-in-ffmpeg-to-specify-a-subtitle-track-that-should-be-shown-by

**Comment by danipragustia** [comment]
Non-subtitle sudah ada dibranch testing
https://github.com/danipragustia/MKVRipa/commit/ed7ad9866c47c0e6190645e6dd61062d9fafc549

Untuk fitur subtitle selective saya akan buat issue baru.
Jadi saya tutup issue ini.
