### ISSUE TITLE
[Bukan Masalah] Setidaknya nama file di releases github dikasih versi

### ISSUE THREAD

**Issue by dhana-exe** [danipragustia/MKVRipa#7]
masalah kecil buat file terlebih yang zip sebaiknya di belakang nama file dikasih versi berapa... jadi jangan sama semua pak :v downloadnya jadi susah :3 (maksudnya bingung ntar di folder ini yang versi berapa gitu kwkwkwkwk

**Comment by danipragustia** [comment]
Terima kasih atas sarannya.

Saya juga berencana untuk itu, sembari membuat script auto-deploy (CI) tapi belum saya upload ke branch testing.

Saya akan tutup issue, jika script sudah merge master (release baru).

**Comment by danipragustia** [comment]
Now script has been added on merge #8 
https://github.com/danipragustia/MKVRipa/commit/18b0a122b3d77f91064e7dc6248782359c111204  build: fix my silly bug and added temp folder to gitignore 
https://github.com/danipragustia/MKVRipa/commit/b390a0050549af7dc38f103f58061481f91ee5db build: added first approach build script

I will close the issue, if facing issue on build script please make new issue.
